//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCave.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentRecord
    {
        public string Isbn13 { get; set; }
        public Nullable<byte> ScholasticGradeHigher { get; set; }
        public string ScholasticGradeLower { get; set; }
        public Nullable<byte> BarnesAgeYoung { get; set; }
        public Nullable<byte> BarnesAgeOld { get; set; }
    
        public virtual BookRecord BookRecord { get; set; }
    }
}
