//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCave.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillRecord
    {
        public Nullable<double> ScholasticGrade { get; set; }
        public string Dra { get; set; }
        public Nullable<short> LexScore { get; set; }
        public string GuidedReading { get; set; }
        public string Isbn13 { get; set; }
        public string LexCode { get; set; }
        public Nullable<System.DateTime> LexUpdate { get; set; }
    
        public virtual BookRecord BookRecord { get; set; }
    }
}
